# enroute_config.yaml

conversion:
  source_format: FHIR_JSON

  # Supported values:
  # FHIR_JSON   - Active / MVP
  # CCDA        - Future
  # HL7V2       - Future
  mode: ANALYZE
  #mode: PROCESS 

intake:
  incoming_directory: data/incoming
  processing_directory: data/processing
  archive_directory: data/archive
  error_directory: data/error

fhir:
  version: R4
  classify_resources: true

ccda:
  enabled: false

hl7v2:
  enabled: false
  
practitioner:
  match:
    identifier_system: "http://hl7.org/fhir/sid/us-npi"

  not_found_action: "DEFAULT"

  default_mapping:
    destination_practitioner_id: '1001'  

organization:
  mapping_mode: "DEFAULT"

  default_mapping:
    destination_organization_id: "1055"  

location:
  mapping_mode: "DEFAULT"

  default_mapping:
    destination_location_id: "PLACEHOLDER"      